# Generated by Django 3.0.8 on 2020-07-12 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuberculosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_vax_date_1_day', models.DateField()),
                ('vax_date_1_day', models.DateTimeField()),
                ('vax_name_1_day', models.CharField(max_length=64)),
                ('symptom_after_vax_1_day', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tuberculosis2005',
            fields=[
                ('tuberculosis_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vax.Tuberculosis')),
                ('expected_vax_date_12_m', models.DateField()),
                ('vax_date_12_m', models.DateField()),
                ('vax_name_12_m', models.CharField(max_length=64)),
                ('symptom_after_vax_12_m', models.TextField()),
                ('expected_vax_date_7_y', models.DateField()),
                ('vax_date_7_y', models.DateField()),
                ('vax_name_7_y', models.CharField(max_length=64)),
                ('symptom_after_vax_7_y', models.TextField()),
                ('expected_vax_date_12_y', models.DateField()),
                ('vax_date_12_y', models.DateField()),
                ('vax_name_12_y', models.CharField(max_length=64)),
                ('symptom_after_vax_12_y', models.TextField()),
            ],
            bases=('vax.tuberculosis',),
        ),
    ]
