# Generated by Django 3.0.8 on 2020-07-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vax', '0002_tuberculosis_tuberculosis2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='HepatitisB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_vax_date_1_day', models.DateField()),
                ('vax_date_1_day', models.DateTimeField()),
                ('vax_name_1_day', models.CharField(max_length=64)),
                ('symptom_after_vax_1_day', models.TextField()),
                ('expected_vax_date_2_m', models.DateField()),
                ('vax_date_2_m', models.DateField()),
                ('vax_name_2_m', models.CharField(max_length=64)),
                ('symptom_after_vax_2_m', models.TextField()),
                ('expected_vax_date_7_m', models.DateField()),
                ('vax_date_7_m', models.DateField()),
                ('vax_name_7_m', models.CharField(max_length=64)),
                ('symptom_after_vax_7_m', models.TextField()),
            ],
        ),
    ]
