# Generated by Django 3.0.8 on 2020-07-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vax', '0003_hepatitisb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildHealthReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_child_review', models.IntegerField(choices=[(1, 'post-birth workup'), (2, 'midwife home visit on the 7th day of life'), (3, 'workup on the 1th month of life'), (4, 'midwife home visit on the 3th month of life'), (5, 'workup on the 6th month of life'), (6, 'workup on the 12th month of life'), (7, 'workup on the 2th year of life'), (8, 'workup on the 4th year of life'), (9, 'workup on the 6th year of life'), (10, 'workup on the 10th year of life'), (11, 'workup on the 15th year of life'), (12, 'workup on the 18th year of life')], default=0)),
                ('exp_workup_day', models.DateField()),
                ('workup_day', models.DateField()),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='HepatitisB',
        ),
        migrations.RemoveField(
            model_name='tuberculosis2005',
            name='tuberculosis_ptr',
        ),
        migrations.AlterField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Tuberculosis',
        ),
        migrations.DeleteModel(
            name='Tuberculosis2005',
        ),
        migrations.AddField(
            model_name='childhealthreview',
            name='child',
            field=models.ManyToManyField(to='vax.Child'),
        ),
    ]
