# Generated by Django 3.0.8 on 2020-07-14 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vax', '0005_vax_vaxcycle_vaxcyclename_vaxname_vaxprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaxprogram',
            name='child',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vax.Child'),
        ),
    ]
