# Generated by Django 3.0.8 on 2020-07-14 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vax', '0006_auto_20200714_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaxprogram',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vax.Child'),
        ),
    ]
