# Generated by Django 3.0.8 on 2020-07-16 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vax', '0007_auto_20200714_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='surname',
            new_name='last_nane',
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vax',
            name='exp_vax_date',
            field=models.DateField(verbose_name='Wymagana data wykonania szczepenia'),
        ),
        migrations.AlterField(
            model_name='vax',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vax.VaxName', verbose_name='Nazwa szczepienia'),
        ),
        migrations.AlterField(
            model_name='vax',
            name='symptom_after_vax',
            field=models.TextField(null=True, verbose_name='Obserwacje po szczepieniu'),
        ),
        migrations.AlterField(
            model_name='vax',
            name='vax_date',
            field=models.DateField(null=True, verbose_name='Data wykonania szczepienia'),
        ),
        migrations.AlterField(
            model_name='vax',
            name='vaxcycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vax.VaxCycle', verbose_name='Cykl dla szczepionki'),
        ),
    ]
