# Generated by Django 3.0.8 on 2020-07-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vax', '0008_auto_20200716_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='last_nane',
        ),
    ]
