# Generated by Django 3.0.8 on 2020-07-22 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vax', '0010_auto_20200717_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='surname',
            new_name='last_name',
        ),
    ]
