# Generated by Django 3.0.8 on 2020-07-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vax', '0011_auto_20200722_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(help_text='yyyy-mm-dd'),
        ),
    ]
