# Generated by Django 3.0.8 on 2020-07-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vax', '0013_auto_20200722_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vax',
            name='exp_vax_date',
            field=models.DateField(null=True, verbose_name='Wymagana data wykonania szczepenia'),
        ),
    ]
