# Generated by Django 3.0.8 on 2020-07-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vax', '0014_auto_20200722_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vax',
            name='exp_vax_date',
            field=models.DateField(null=True, verbose_name='Wymagana data szczepenia'),
        ),
        migrations.AlterField(
            model_name='vax',
            name='symptom_after_vax',
            field=models.TextField(null=True, verbose_name='Obserwacje'),
        ),
        migrations.AlterField(
            model_name='vax',
            name='vax_date',
            field=models.DateField(null=True, verbose_name='Data szczepienia'),
        ),
    ]
