# Generated by Django 3.0.8 on 2020-07-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vax', '0015_auto_20200723_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vax',
            name='symptom_after_vax',
            field=models.TextField(blank=True, null=True, verbose_name='Obserwacje'),
        ),
        migrations.AlterField(
            model_name='vax',
            name='vax_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data szczepienia'),
        ),
    ]
