# Generated by Django 3.0.8 on 2020-07-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vax', '0016_auto_20200723_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vax',
            name='exp_vax_date',
            field=models.DateField(help_text='YYYY-MM-DD', null=True, verbose_name='Wymagana data szczepenia'),
        ),
        migrations.AlterField(
            model_name='vax',
            name='vax_date',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True, verbose_name='Data szczepienia'),
        ),
    ]
