# Generated by Django 3.0.8 on 2020-07-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vax', '0018_auto_20200724_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='sex',
            field=models.CharField(choices=[('M', 'mężczyzna'), ('F', 'kobieta')], max_length=1),
        ),
        migrations.AlterField(
            model_name='childhealthreview',
            name='name_child_review',
            field=models.IntegerField(choices=[(1, 'Badanie po urodzeniu'), (2, 'Domowa wizyta położnej w 7 dniu życia'), (3, 'Badanie w 1 miesiącu życia'), (4, 'Domowa wizyta położnej w 3 miesiącu życia'), (5, 'Badanie w 6 miesiącu życia'), (6, 'Badanie w 12 miesiącu życia'), (7, 'Badanie w 2 roku życia'), (8, 'Badanie w 4 roku życia'), (9, 'Badanie w 6 roku życia (przed pójściem do szkoły)'), (10, 'Badanie w 10 roku życia'), (11, 'Badanie w 15 roku życia'), (12, 'Badanie w 18 roku życia')], default=0),
        ),
        migrations.AlterField(
            model_name='childhealthreview',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Obserwacje i zalecenia'),
        ),
    ]
