# Generated by Django 3.0.8 on 2020-07-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vax', '0019_auto_20200725_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='email',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
